import { STORAGE_KEYS } from '../persistence/storageKeys';
import type { SyncMessage, SyncEventType } from './syncEvents';
import { localEventBus } from './localEventBus';

export const CURRENT_TAB_ID = `tab-${Math.random().toString(36).substring(2, 9)}`;

export class BroadcastSyncEngine {
  private channel: BroadcastChannel | null = null;
  private isSupported: boolean = false;
  private listeners: Set<(msg: SyncMessage) => void> = new Set();

  constructor() {
    this.init();
  }

  private init(): void {
    if (typeof window !== 'undefined' && 'BroadcastChannel' in window) {
      try {
        this.channel = new BroadcastChannel(STORAGE_KEYS.SYNC_CHANNEL);
        this.channel.onmessage = (event: MessageEvent<SyncMessage>) => {
          this.handleIncoming(event.data);
        };
        this.isSupported = true;
      } catch (e) {
        console.warn('[SYNC] BroadcastChannel initialization failed, falling back to storage events', e);
        this.channel = null;
        this.isSupported = false;
      }
    }

    // Storage event fallback (for browsers without BroadcastChannel or cross-tab fallback)
    if (typeof window !== 'undefined') {
      window.addEventListener('storage', (e: StorageEvent) => {
        if (e.key === STORAGE_KEYS.METADATA && e.newValue) {
          try {
            const meta = JSON.parse(e.newValue);
            this.handleIncoming({
              id: `sync-stor-${Date.now()}`,
              type: 'STATE_UPDATED',
              timestamp: meta.lastUpdatedAt || new Date().toISOString(),
              senderTabId: 'external_tab',
              stateVersion: meta.stateVersion || 0,
            });
          } catch {
            // ignore
          }
        }
      });
    }
  }

  private handleIncoming(message: SyncMessage): void {
    // Ignore events generated by this exact tab
    if (message.senderTabId === CURRENT_TAB_ID) {
      return;
    }

    // Dispatch locally
    localEventBus.emit(message.type, message.payload);
    localEventBus.emit('STATE_UPDATED', message.payload);

    this.listeners.forEach((listener) => {
      try {
        listener(message);
      } catch (e) {
        console.error('[SYNC] Error in broadcast listener:', e);
      }
    });
  }

  broadcast(type: SyncEventType, stateVersion: number, payload?: unknown, entityType?: string, entityId?: string): void {
    const message: SyncMessage = {
      id: `msg-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
      type,
      timestamp: new Date().toISOString(),
      senderTabId: CURRENT_TAB_ID,
      stateVersion,
      entityType,
      entityId,
      payload,
    };

    // 1. Post to BroadcastChannel if available
    if (this.channel) {
      try {
        this.channel.postMessage(message);
      } catch (e) {
        console.error('[SYNC] Failed posting message to BroadcastChannel:', e);
      }
    }

    // 2. Dispatch to same-tab local event bus
    localEventBus.emit(type, payload);
    localEventBus.emit('STATE_UPDATED', payload);
  }

  subscribe(listener: (msg: SyncMessage) => void): () => void {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  }

  getChannelStatus(): { isSupported: boolean; tabId: string } {
    return {
      isSupported: this.isSupported,
      tabId: CURRENT_TAB_ID,
    };
  }
}

export const syncEngine = new BroadcastSyncEngine();
