import type { RaktSetuLocalState, CriticalAlert, AppSettings } from '../types/admin';
import type { Organization } from '../types/organization';
import type { BloodBank } from '../types/matching';
import type { HospitalInventoryItem } from '../data/hospitalInventory';
import type { BloodInventoryTransaction } from '../types/transaction';
import type { BloodRequest } from '../types/bloodRequest';
import type { BloodReservation } from '../types/reservation';
import type { BloodTransfer } from '../types/transfer';
import type { AuditLog } from '../types/audit';
import { CURRENT_SCHEMA_VERSION } from './storageKeys';

export const INITIAL_SETTINGS: AppSettings = {
  autoSync: true,
  lowStockThresholdLitres: 2.0,
  criticalStockThresholdLitres: 1.0,
  reservationExpiryHours: 4,
  networkProtectionEnabled: true,
  demoMode: true,
  schemaVersion: CURRENT_SCHEMA_VERSION,
};

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'HSP-00124',
    name: 'CityCare Hospital & Trauma Center',
    code: 'CCH-NGP',
    type: 'hospital',
    status: 'VERIFIED',
    licenseNumber: 'MH-NGP-HSP-2024-991',
    location: {
      address: 'Plot 12, Medical Square, Ramdaspeth',
      city: 'Nagpur',
      state: 'Maharashtra',
      pincode: '440010',
      coordinates: { lat: 21.135, lng: 79.082, x: 42, y: 38 },
    },
    contact: {
      primaryPhone: '+91 712 245 8890',
      emergencyPhone: '+91 712 245 8899',
      email: 'director@metrotrauma.org',
      website: 'https://citycare.hospital.local',
    },
    registeredAt: '2026-08-15T09:00:00Z',
    verifiedAt: '2026-08-16T14:30:00Z',
    verifiedBy: 'RaktSetu State Admin',
    stats: {
      totalInventoryUnits: 17.5,
      criticalStockGroups: ['O+'],
      activeRequestsCount: 1,
      completedTransfersCount: 14,
      lastActiveAt: '2026-10-03T11:45:00Z',
    },
    notes: 'Level 1 Trauma resuscitation center serving Central Nagpur corridor.',
  },
  {
    id: 'HSP-00125',
    name: 'Sunrise Multispeciality Hospital',
    code: 'SMH-NGP',
    type: 'hospital',
    status: 'VERIFIED',
    licenseNumber: 'MH-NGP-HSP-2023-412',
    location: {
      address: 'Central Avenue Road, Gandhibagh',
      city: 'Nagpur',
      state: 'Maharashtra',
      pincode: '440002',
      coordinates: { lat: 21.152, lng: 79.114, x: 58, y: 28 },
    },
    contact: {
      primaryPhone: '+91 712 272 1100',
      emergencyPhone: '+91 712 272 1109',
      email: 'bloodtransfusion@sunrisemulti.org',
    },
    registeredAt: '2026-07-20T10:00:00Z',
    verifiedAt: '2026-07-21T11:00:00Z',
    verifiedBy: 'RaktSetu State Admin',
    stats: {
      totalInventoryUnits: 22.0,
      criticalStockGroups: [],
      activeRequestsCount: 1,
      completedTransfersCount: 9,
      lastActiveAt: '2026-10-03T10:30:00Z',
    },
    notes: 'General and Cardiothoracic hospital with 24/7 operating rooms.',
  },
  {
    id: 'HSP-00126',
    name: 'Metro General Healthcare',
    code: 'MGH-WRD',
    type: 'hospital',
    status: 'PENDING',
    licenseNumber: 'MH-WRD-HSP-2026-081',
    location: {
      address: 'Samarth Nagar, Sevagram Road',
      city: 'Wardha',
      state: 'Maharashtra',
      pincode: '442001',
      coordinates: { lat: 20.745, lng: 78.602, x: 22, y: 72 },
    },
    contact: {
      primaryPhone: '+91 7152 240 550',
      email: 'admin@metrohealthcare-wrd.org',
    },
    registeredAt: '2026-10-02T16:20:00Z',
    stats: {
      totalInventoryUnits: 8.0,
      criticalStockGroups: ['O-', 'AB-'],
      activeRequestsCount: 0,
      completedTransfersCount: 0,
      lastActiveAt: '2026-10-02T16:20:00Z',
    },
    notes: 'New peripheral hospital requesting network onboarding and cross-matching credentials.',
  },
  {
    id: 'bank-nagpur-regional',
    name: 'Nagpur Regional Blood Centre',
    code: 'NRBC-01',
    type: 'blood_bank',
    status: 'VERIFIED',
    licenseNumber: 'MH-BB-NGP-001',
    location: {
      address: 'Near Government Medical College, Hanuman Nagar',
      city: 'Nagpur',
      state: 'Maharashtra',
      pincode: '440009',
      coordinates: { lat: 21.127, lng: 79.096, x: 48, y: 45 },
    },
    contact: {
      primaryPhone: '+91 712 274 4401',
      emergencyPhone: '+91 712 274 4409',
      email: 'operations@nagpurbloodcentre.org',
    },
    registeredAt: '2026-06-01T08:00:00Z',
    verifiedAt: '2026-06-02T10:00:00Z',
    verifiedBy: 'RaktSetu State Admin',
    stats: {
      totalInventoryUnits: 104.5,
      criticalStockGroups: [],
      activeRequestsCount: 2,
      completedTransfersCount: 38,
      lastActiveAt: '2026-10-03T12:00:00Z',
    },
    notes: 'Primary regional component separation and red blood cell preservation hub.',
  },
  {
    id: 'bank-central-city',
    name: 'Central City Blood Bank',
    code: 'CCBB-02',
    type: 'blood_bank',
    status: 'VERIFIED',
    licenseNumber: 'MH-BB-NGP-002',
    location: {
      address: 'Sitabuldi Interchange, Wardha Road',
      city: 'Nagpur Central',
      state: 'Maharashtra',
      pincode: '440012',
      coordinates: { lat: 21.145, lng: 79.088, x: 46, y: 32 },
    },
    contact: {
      primaryPhone: '+91 712 253 9820',
      email: 'dispatch@centralcityblood.org',
    },
    registeredAt: '2026-06-15T09:30:00Z',
    verifiedAt: '2026-06-16T12:00:00Z',
    verifiedBy: 'RaktSetu State Admin',
    stats: {
      totalInventoryUnits: 68.0,
      criticalStockGroups: ['O-'],
      activeRequestsCount: 1,
      completedTransfersCount: 29,
      lastActiveAt: '2026-10-03T11:50:00Z',
    },
    notes: 'City center high-turnover preservation bank serving urban emergency care units.',
  },
  {
    id: 'bank-vidarbha-life',
    name: 'Vidarbha Life Blood Bank',
    code: 'VLBB-03',
    type: 'blood_bank',
    status: 'VERIFIED',
    licenseNumber: 'MH-BB-NGP-003',
    location: {
      address: 'Plot 44, Electronic Zone, Hingna Road',
      city: 'MIDC Hingna',
      state: 'Maharashtra',
      pincode: '440028',
      coordinates: { lat: 21.098, lng: 78.995, x: 26, y: 60 },
    },
    contact: {
      primaryPhone: '+91 712 288 1205',
      email: 'supplies@vidarbhalife.org',
    },
    registeredAt: '2026-08-01T11:00:00Z',
    verifiedAt: '2026-08-02T15:00:00Z',
    verifiedBy: 'RaktSetu State Admin',
    stats: {
      totalInventoryUnits: 82.5,
      criticalStockGroups: [],
      activeRequestsCount: 0,
      completedTransfersCount: 16,
      lastActiveAt: '2026-10-03T10:45:00Z',
    },
    notes: 'Long-shelf-life strategic reserve facility with refrigerated distribution vans.',
  },
];

export const INITIAL_BLOOD_BANKS_FULL: BloodBank[] = [
  {
    id: 'bank-nagpur-regional',
    name: 'Nagpur Regional Blood Centre',
    city: 'Nagpur',
    address: 'Near Government Medical College, Hanuman Nagar, Nagpur',
    distanceKm: 18.2,
    contactPhone: '+91 712 274 4401',
    rating: 4.9,
    responseTimeMinutes: 25,
    networkDemand: 'Moderate',
    inventories: {
      'O+': { bloodGroup: 'O+', physicalStock: 24.0, reservedStock: 4.0, availableStock: 20.0, predictedDemand24h: 8.5, shortageRisk: 'low' },
      'O-': { bloodGroup: 'O-', physicalStock: 8.0, reservedStock: 1.0, availableStock: 7.0, predictedDemand24h: 3.0, shortageRisk: 'monitor' },
      'A+': { bloodGroup: 'A+', physicalStock: 18.0, reservedStock: 2.0, availableStock: 16.0, predictedDemand24h: 6.0, shortageRisk: 'low' },
      'A-': { bloodGroup: 'A-', physicalStock: 6.0, reservedStock: 0.5, availableStock: 5.5, predictedDemand24h: 2.0, shortageRisk: 'low' },
      'B+': { bloodGroup: 'B+', physicalStock: 22.0, reservedStock: 3.0, availableStock: 19.0, predictedDemand24h: 7.0, shortageRisk: 'low' },
      'B-': { bloodGroup: 'B-', physicalStock: 7.0, reservedStock: 1.0, availableStock: 6.0, predictedDemand24h: 2.5, shortageRisk: 'monitor' },
      'AB+': { bloodGroup: 'AB+', physicalStock: 12.0, reservedStock: 1.0, availableStock: 11.0, predictedDemand24h: 4.0, shortageRisk: 'low' },
      'AB-': { bloodGroup: 'AB-', physicalStock: 5.0, reservedStock: 0.5, availableStock: 4.5, predictedDemand24h: 1.5, shortageRisk: 'low' },
    },
  },
  {
    id: 'bank-central-city',
    name: 'Central City Blood Bank',
    city: 'Nagpur Central',
    address: 'Sitabuldi Interchange, Wardha Road, Nagpur',
    distanceKm: 12.4,
    contactPhone: '+91 712 253 9820',
    rating: 4.7,
    responseTimeMinutes: 18,
    networkDemand: 'High',
    inventories: {
      'O+': { bloodGroup: 'O+', physicalStock: 16.0, reservedStock: 2.0, availableStock: 14.0, predictedDemand24h: 13.0, shortageRisk: 'high' },
      'O-': { bloodGroup: 'O-', physicalStock: 4.0, reservedStock: 1.0, availableStock: 3.0, predictedDemand24h: 2.8, shortageRisk: 'high' },
      'A+': { bloodGroup: 'A+', physicalStock: 14.0, reservedStock: 2.0, availableStock: 12.0, predictedDemand24h: 7.0, shortageRisk: 'monitor' },
      'A-': { bloodGroup: 'A-', physicalStock: 4.0, reservedStock: 0.5, availableStock: 3.5, predictedDemand24h: 1.5, shortageRisk: 'low' },
      'B+': { bloodGroup: 'B+', physicalStock: 15.0, reservedStock: 3.0, availableStock: 12.0, predictedDemand24h: 8.0, shortageRisk: 'monitor' },
      'B-': { bloodGroup: 'B-', physicalStock: 3.5, reservedStock: 1.0, availableStock: 2.5, predictedDemand24h: 2.0, shortageRisk: 'high' },
      'AB+': { bloodGroup: 'AB+', physicalStock: 9.0, reservedStock: 1.0, availableStock: 8.0, predictedDemand24h: 3.5, shortageRisk: 'low' },
      'AB-': { bloodGroup: 'AB-', physicalStock: 3.0, reservedStock: 0.5, availableStock: 2.5, predictedDemand24h: 1.2, shortageRisk: 'monitor' },
    },
  },
  {
    id: 'bank-vidarbha-life',
    name: 'Vidarbha Life Blood Bank',
    city: 'MIDC Hingna',
    address: 'Plot 44, Electronic Zone, Hingna Road, Nagpur',
    distanceKm: 27.5,
    contactPhone: '+91 712 288 1205',
    rating: 4.8,
    responseTimeMinutes: 38,
    networkDemand: 'Low',
    inventories: {
      'O+': { bloodGroup: 'O+', physicalStock: 20.0, reservedStock: 1.0, availableStock: 19.0, predictedDemand24h: 5.0, shortageRisk: 'low' },
      'O-': { bloodGroup: 'O-', physicalStock: 5.0, reservedStock: 0.5, availableStock: 4.5, predictedDemand24h: 1.8, shortageRisk: 'low' },
      'A+': { bloodGroup: 'A+', physicalStock: 16.0, reservedStock: 1.0, availableStock: 15.0, predictedDemand24h: 4.5, shortageRisk: 'low' },
      'A-': { bloodGroup: 'A-', physicalStock: 5.0, reservedStock: 0.5, availableStock: 4.5, predictedDemand24h: 1.2, shortageRisk: 'low' },
      'B+': { bloodGroup: 'B+', physicalStock: 18.0, reservedStock: 2.0, availableStock: 16.0, predictedDemand24h: 5.5, shortageRisk: 'low' },
      'B-': { bloodGroup: 'B-', physicalStock: 5.5, reservedStock: 0.5, availableStock: 5.0, predictedDemand24h: 1.5, shortageRisk: 'low' },
      'AB+': { bloodGroup: 'AB+', physicalStock: 9.5, reservedStock: 0.5, availableStock: 9.0, predictedDemand24h: 2.5, shortageRisk: 'low' },
      'AB-': { bloodGroup: 'AB-', physicalStock: 3.5, reservedStock: 0.5, availableStock: 3.0, predictedDemand24h: 1.0, shortageRisk: 'low' },
    },
  },
];

export const INITIAL_HOSPITAL_INVENTORY: HospitalInventoryItem[] = [
  {
    id: 'inv-oplus',
    organizationId: 'HSP-00124',
    bloodGroup: 'O+',
    availableQuantity: 4.0, // After verified issues: 10.0 -> 8.0 -> 7.0 -> 5.0 -> 4.0 L
    reservedQuantity: 0.5,
    unit: 'L',
    expiryDate: '2026-10-28',
    demandLevel: 'High',
    status: 'attention',
    prediction: {
      predictedDepletionHours: 2.2,
      trend: 'depleting',
    },
    updatedAt: '2026-10-03T11:42:00Z',
    notes: 'Elevated trauma transfusion rate in last 24h. Stockout risk high.',
  },
  {
    id: 'inv-ominus',
    organizationId: 'HSP-00124',
    bloodGroup: 'O-',
    availableQuantity: 1.2,
    reservedQuantity: 0.3,
    unit: 'L',
    expiryDate: '2026-10-22',
    demandLevel: 'High',
    status: 'monitor',
    prediction: {
      predictedDepletionHours: 11.5,
      trend: 'depleting',
    },
    updatedAt: '2026-10-03T10:15:00Z',
  },
  {
    id: 'inv-aplus',
    organizationId: 'HSP-00124',
    bloodGroup: 'A+',
    availableQuantity: 3.0,
    reservedQuantity: 0.5,
    unit: 'L',
    expiryDate: '2026-10-24',
    demandLevel: 'Medium',
    status: 'healthy',
    prediction: {
      predictedDepletionHours: 48,
      trend: 'stable',
    },
    updatedAt: '2026-10-03T10:15:00Z',
  },
  {
    id: 'inv-aminus',
    organizationId: 'HSP-00124',
    bloodGroup: 'A-',
    availableQuantity: 1.5,
    reservedQuantity: 0.2,
    unit: 'L',
    expiryDate: '2026-10-19',
    demandLevel: 'Low',
    status: 'healthy',
    prediction: {
      predictedDepletionHours: 72,
      trend: 'stable',
    },
    updatedAt: '2026-10-03T09:30:00Z',
  },
  {
    id: 'inv-bplus',
    organizationId: 'HSP-00124',
    bloodGroup: 'B+',
    availableQuantity: 3.5,
    reservedQuantity: 0.5,
    unit: 'L',
    expiryDate: '2026-10-26',
    demandLevel: 'High',
    status: 'monitor',
    prediction: {
      predictedDepletionHours: 14.0,
      trend: 'depleting',
    },
    updatedAt: '2026-10-03T11:00:00Z',
  },
  {
    id: 'inv-bminus',
    organizationId: 'HSP-00124',
    bloodGroup: 'B-',
    availableQuantity: 1.0,
    reservedQuantity: 0.2,
    unit: 'L',
    expiryDate: '2026-10-05', // near expiry!
    demandLevel: 'Low',
    status: 'monitor',
    prediction: {
      predictedDepletionHours: 54,
      trend: 'stable',
    },
    updatedAt: '2026-10-03T08:00:00Z',
    notes: 'Near expiry window (48h). Candidate for redistribution.',
  },
  {
    id: 'inv-abplus',
    organizationId: 'HSP-00124',
    bloodGroup: 'AB+',
    availableQuantity: 2.5,
    reservedQuantity: 0.2,
    unit: 'L',
    expiryDate: '2026-10-30',
    demandLevel: 'Low',
    status: 'healthy',
    prediction: {
      predictedDepletionHours: 96,
      trend: 'stable',
    },
    updatedAt: '2026-10-03T10:15:00Z',
  },
  {
    id: 'inv-abminus',
    organizationId: 'HSP-00124',
    bloodGroup: 'AB-',
    availableQuantity: 0.8,
    reservedQuantity: 0.1,
    unit: 'L',
    expiryDate: '2026-10-20',
    demandLevel: 'Low',
    status: 'healthy',
    prediction: {
      predictedDepletionHours: 80,
      trend: 'stable',
    },
    updatedAt: '2026-10-03T09:00:00Z',
  },
];

export const INITIAL_TRANSACTIONS: BloodInventoryTransaction[] = [
  {
    id: 'tx-1001',
    transactionId: 'TXN-20261003-10241',
    organizationId: 'HSP-00124',
    hospitalId: 'HSP-00124',
    bloodGroup: 'O+',
    transactionType: 'ISSUED',
    quantityLitres: 2.0,
    quantityBefore: 10.0,
    quantityAfter: 8.0,
    referenceType: 'PATIENT_TRANSFUSION',
    referenceId: 'P1024',
    patientCaseId: 'P1024',
    department: 'Emergency Trauma ICU',
    reason: 'Emergency transfusion - polytrauma motor collision',
    notes: 'Rapid infusion protocol activated. Pre-transfusion vitals documented.',
    performedBy: 'Dr. Ramesh Sharma (Trauma Lead)',
    verifiedBy: 'Sister Philomena (Head Nurse, ICU)',
    status: 'VERIFIED',
    occurredAt: '2026-10-03T10:00:00Z',
    createdAt: '2026-10-03T10:02:15Z',
  },
  {
    id: 'tx-1002',
    transactionId: 'TXN-20261003-10242',
    organizationId: 'HSP-00124',
    hospitalId: 'HSP-00124',
    bloodGroup: 'O+',
    transactionType: 'ISSUED',
    quantityLitres: 1.0,
    quantityBefore: 8.0,
    quantityAfter: 7.0,
    referenceType: 'PATIENT_TRANSFUSION',
    referenceId: 'P1025',
    patientCaseId: 'P1025',
    department: 'Emergency Room (ER)',
    reason: 'Acute GI hemorrhage resuscitation',
    performedBy: 'Dr. Sunita Deshmukh',
    verifiedBy: 'Sister Philomena',
    status: 'VERIFIED',
    occurredAt: '2026-10-03T11:00:00Z',
    createdAt: '2026-10-03T11:01:45Z',
  },
  {
    id: 'tx-1003',
    transactionId: 'TXN-20261003-10243',
    organizationId: 'HSP-00124',
    hospitalId: 'HSP-00124',
    bloodGroup: 'O+',
    transactionType: 'ISSUED',
    quantityLitres: 2.0,
    quantityBefore: 7.0,
    quantityAfter: 5.0,
    referenceType: 'PATIENT_TRANSFUSION',
    referenceId: 'P1026',
    patientCaseId: 'P1026',
    department: 'Cardiothoracic Surgery OR',
    reason: 'Cardiopulmonary bypass prime & hemorrhage control',
    performedBy: 'Dr. Vivek Kulkarni (Surgeon)',
    verifiedBy: 'Dr. Aarti Patel (Anesthetist)',
    status: 'VERIFIED',
    occurredAt: '2026-10-03T11:20:00Z',
    createdAt: '2026-10-03T11:22:10Z',
  },
  {
    id: 'tx-1004',
    transactionId: 'TXN-20261003-10244',
    organizationId: 'HSP-00124',
    hospitalId: 'HSP-00124',
    bloodGroup: 'O+',
    transactionType: 'ISSUED',
    quantityLitres: 1.0,
    quantityBefore: 5.0,
    quantityAfter: 4.0,
    referenceType: 'PATIENT_TRANSFUSION',
    referenceId: 'P1027',
    patientCaseId: 'P1027',
    department: 'Obstetrics & Labor Ward',
    reason: 'Postpartum hemorrhage emergency protocol',
    performedBy: 'Dr. Kavita Joshi (Obs & Gyn)',
    verifiedBy: 'Sister Meena (Labor Lead)',
    status: 'VERIFIED',
    occurredAt: '2026-10-03T11:40:00Z',
    createdAt: '2026-10-03T11:42:00Z',
  },
  {
    id: 'tx-1005',
    transactionId: 'TXN-20261003-10245',
    organizationId: 'HSP-00124',
    hospitalId: 'HSP-00124',
    bloodGroup: 'A+',
    transactionType: 'RECEIVED',
    quantityLitres: 1.5,
    quantityBefore: 1.5,
    quantityAfter: 3.0,
    referenceType: 'NETWORK_REFILL',
    referenceId: 'TR-202610-101',
    department: 'Hospital Central Blood Bank',
    reason: 'Routine scheduled regional depot replenishment',
    performedBy: 'Technician Rajesh Ingle',
    verifiedBy: 'Dr. Anand Verma',
    status: 'VERIFIED',
    occurredAt: '2026-10-03T09:15:00Z',
    createdAt: '2026-10-03T09:17:30Z',
  },
];

export const INITIAL_REQUESTS: BloodRequest[] = [
  {
    id: 'req-801',
    displayId: 'REQ-202610-801',
    hospitalId: 'HSP-00124',
    hospitalName: 'CityCare Hospital & Trauma Center',
    hospitalCity: 'Nagpur',
    deliveryLocation: 'Medical Square, Ramdaspeth',
    bloodGroup: 'O+',
    quantityLitres: 4.0,
    priority: 'emergency',
    status: 'approved',
    requiredBy: '2026-10-03T15:00:00Z',
    reason: 'Emergency Trauma Resuscitation Buffer Depleted',
    createdAt: '2026-10-03T11:55:00Z',
    updatedAt: '2026-10-03T12:05:00Z',
    submittedBy: 'CityCare Hospital Staff',
    activities: [
      {
        id: 'act-1',
        requestId: 'req-801',
        type: 'created',
        title: 'Requisition Created',
        description: 'Requisition submitted for 4.0 L O+ predictive replenishment.',
        timestamp: '2026-10-03T11:55:00Z',
      },
      {
        id: 'act-2',
        requestId: 'req-801',
        type: 'approval',
        title: 'Requisition Approved',
        description: 'Requisition approved. Initiating candidate blood bank matching.',
        timestamp: '2026-10-03T12:05:00Z',
      },
    ],
  },
  {
    id: 'req-802',
    displayId: 'REQ-202610-802',
    hospitalId: 'HSP-00125',
    hospitalName: 'Sunrise Multispeciality Hospital',
    hospitalCity: 'Nagpur',
    deliveryLocation: 'Central Avenue Road, Gandhibagh',
    bloodGroup: 'B+',
    quantityLitres: 2.0,
    priority: 'urgent',
    status: 'pending_approval',
    requiredBy: '2026-10-03T18:00:00Z',
    reason: 'Scheduled Onco-Surgery Cross-Match Reserve',
    createdAt: '2026-10-03T11:15:00Z',
    updatedAt: '2026-10-03T11:15:00Z',
    submittedBy: 'Sunrise Multispeciality Staff',
    activities: [
      {
        id: 'act-3',
        requestId: 'req-802',
        type: 'created',
        title: 'Requisition Created',
        description: 'Request submitted for scheduled elective surgical reserve.',
        timestamp: '2026-10-03T11:15:00Z',
      },
    ],
  },
  {
    id: 'req-803',
    displayId: 'REQ-202610-803',
    hospitalId: 'HSP-00124',
    hospitalName: 'CityCare Hospital & Trauma Center',
    hospitalCity: 'Nagpur',
    deliveryLocation: 'Medical Square, Ramdaspeth',
    bloodGroup: 'O-',
    quantityLitres: 1.5,
    priority: 'emergency',
    status: 'completed',
    requiredBy: '2026-10-02T21:00:00Z',
    reason: 'Pediatric ICU Hypovolemic Shock Resuscitation',
    createdAt: '2026-10-02T18:00:00Z',
    updatedAt: '2026-10-02T19:40:00Z',
    submittedBy: 'CityCare Hospital Staff',
    activities: [
      {
        id: 'act-4',
        requestId: 'req-803',
        type: 'created',
        title: 'Requisition Created',
        description: 'Critical emergency requisition for 1.5 L O-.',
        timestamp: '2026-10-02T18:00:00Z',
      },
      {
        id: 'act-5',
        requestId: 'req-803',
        type: 'status_change',
        title: 'Consignment Delivered',
        description: 'Physical delivery verified and ingested into hospital inventory.',
        timestamp: '2026-10-02T19:40:00Z',
      },
    ],
  },
];

export const INITIAL_RESERVATIONS: BloodReservation[] = [
  {
    id: 'res-201',
    reservationId: 'RES-202610-201',
    requestId: 'REQ-202610-801',
    bloodBankId: 'bank-nagpur-regional',
    bloodBankName: 'Nagpur Regional Blood Centre',
    hospitalId: 'HSP-00124',
    hospitalName: 'CityCare Hospital & Trauma Center',
    bloodGroup: 'O+',
    quantityLitres: 4.0,
    status: 'ACTIVE',
    expiresAt: '2026-10-03T16:00:00Z',
    createdAt: '2026-10-03T12:08:00Z',
    updatedAt: '2026-10-03T12:08:00Z',
    createdBy: 'RaktSetu Smart Allocation Engine',
  },
];

export const INITIAL_TRANSFERS: BloodTransfer[] = [
  {
    id: 'tr-301',
    transferId: 'TR-202610-301',
    requestId: 'REQ-202610-801',
    reservationId: 'RES-202610-201',
    fromOrganizationId: 'bank-nagpur-regional',
    fromOrganizationName: 'Nagpur Regional Blood Centre',
    toOrganizationId: 'HSP-00124',
    toOrganizationName: 'CityCare Hospital & Trauma Center',
    bloodGroup: 'O+',
    quantityUnits: 4.0,
    status: 'IN_TRANSIT',
    urgency: 'CRITICAL',
    dispatchedAt: '2026-10-03T12:12:00Z',
    estimatedArrivalMinutes: 18,
    temperatureColdChainCelsius: 3.8,
    courierDetails: {
      carrier: 'LifeLink Cold Chain Express',
      trackingRef: 'LL-CC-99412',
      contactNumber: '+91 98220 11984',
    },
    notes: 'Refrigerated van unit en route via Wardha Road bypass. Temp alarm nominal.',
    createdAt: '2026-10-03T12:10:00Z',
    updatedAt: '2026-10-03T12:12:00Z',
  },
  {
    id: 'tr-302',
    transferId: 'TR-202610-302',
    requestId: 'REQ-202610-803',
    fromOrganizationId: 'bank-central-city',
    fromOrganizationName: 'Central City Blood Bank',
    toOrganizationId: 'HSP-00124',
    toOrganizationName: 'CityCare Hospital & Trauma Center',
    bloodGroup: 'O-',
    quantityUnits: 1.5,
    status: 'DELIVERED',
    urgency: 'CRITICAL',
    dispatchedAt: '2026-10-02T18:45:00Z',
    deliveredAt: '2026-10-02T19:35:00Z',
    temperatureColdChainCelsius: 3.4,
    notes: 'Delivered and verified. Ingested under transaction TXN-20261002-998.',
    createdAt: '2026-10-02T18:40:00Z',
    updatedAt: '2026-10-02T19:35:00Z',
  },
];

export const INITIAL_ALERTS: CriticalAlert[] = [
  {
    id: 'alt-001',
    type: 'CRITICAL_STOCKOUT',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    title: 'O+ Rapid Stockout Warning',
    message: 'CityCare Hospital has only 4.0 L O+ remaining with high consumption rate (1.8 L/hr). Estimated coverage ~2.2 hours.',
    organizationId: 'HSP-00124',
    organizationName: 'CityCare Hospital & Trauma Center',
    bloodGroup: 'O+',
    createdAt: '2026-10-03T11:45:00Z',
    reason: 'Verified inpatient consumption consumed 6.0 L in 2.5 hours. Trauma resuscitation ICU buffer depleted.',
    impactExplanation: 'Imminent risk of zero available units for uncrossmatched trauma emergencies unless replenished immediately.',
    recommendedAction: 'Expedite in-transit transfer TR-202610-301 (4.0 L from Nagpur Regional Blood Centre).',
    relatedEntityType: 'INVENTORY',
    relatedEntityId: 'inv-oplus',
    deduplicationKey: 'CRITICAL_STOCKOUT:HSP-00124:O+',
  },
  {
    id: 'alt-002',
    type: 'EXPIRY_RISK',
    severity: 'WARNING',
    status: 'ACTIVE',
    title: 'B- Unit Expiring in < 48 Hours',
    message: '1.0 L B- at CityCare Hospital expires on 2026-10-05. Local B- demand is currently low.',
    organizationId: 'HSP-00124',
    organizationName: 'CityCare Hospital & Trauma Center',
    bloodGroup: 'B-',
    createdAt: '2026-10-03T08:00:00Z',
    reason: 'Unit batch has reached 33 days preservation threshold without assigned cross-match schedule.',
    impactExplanation: 'Scarce rare group blood will expire unless redistributed to high-volume oncology or surgery node.',
    recommendedAction: 'Propose automated network redistribution to Sunrise Multispeciality Hospital.',
    relatedEntityType: 'INVENTORY',
    relatedEntityId: 'inv-bminus',
    deduplicationKey: 'EXPIRY_RISK:HSP-00124:B-',
  },
  {
    id: 'alt-003',
    type: 'ORGANIZATION_VERIFICATION',
    severity: 'MONITOR',
    status: 'ACTIVE',
    title: 'New Hospital Verification Pending',
    message: 'Metro General Healthcare (Wardha) submitted registration documents for network verification.',
    organizationId: 'HSP-00126',
    organizationName: 'Metro General Healthcare',
    createdAt: '2026-10-02T16:20:00Z',
    reason: 'State medical council license MH-WRD-HSP-2026-081 pending administrator compliance verification.',
    impactExplanation: 'Hospital cannot initiate automated cross-bank blood reservations until authorized.',
    recommendedAction: 'Review statutory license documentation in Organization Verification portal.',
    relatedEntityType: 'ORGANIZATION',
    relatedEntityId: 'HSP-00126',
    deduplicationKey: 'ORGANIZATION_VERIFICATION:HSP-00126',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    timestamp: '2026-10-03T12:12:00Z',
    actorId: 'usr-bank-lead-01',
    actorName: 'Dr. Sandeep Deshpande (Bank Director)',
    actorRole: 'blood_bank',
    organizationId: 'bank-nagpur-regional',
    organizationName: 'Nagpur Regional Blood Centre',
    action: 'TRANSFER_DISPATCHED',
    entityType: 'TRANSFER',
    entityId: 'TR-202610-301',
    severity: 'NOTICE',
    previousState: { status: 'SCHEDULED' },
    newState: { status: 'IN_TRANSIT', carrier: 'LifeLink Cold Chain Express' },
    reason: 'Dispatched 4.0 L O+ for emergency replenishment at CityCare Hospital.',
  },
  {
    id: 'aud-002',
    timestamp: '2026-10-03T12:08:00Z',
    actorId: 'usr-sys-alloc',
    actorName: 'RaktSetu Smart Load Balancer',
    actorRole: 'admin',
    organizationId: 'RaktSetu-Network',
    action: 'RESERVATION_CREATED',
    entityType: 'RESERVATION',
    entityId: 'RES-202610-201',
    severity: 'INFO',
    newState: { quantityLitres: 4.0, bloodGroup: 'O+', expiresAt: '2026-10-03T16:00:00Z' },
    reason: 'Atomic reservation locked at Nagpur Regional Blood Centre. Safe allocation verified.',
  },
  {
    id: 'aud-003',
    timestamp: '2026-10-03T12:05:00Z',
    actorId: 'usr-admin-01',
    actorName: 'Alhaj Baig (Regional Director)',
    actorRole: 'admin',
    organizationId: 'RaktSetu-Network',
    organizationName: 'RaktSetu Regional Network Command',
    action: 'REQUEST_APPROVED',
    entityType: 'REQUEST',
    entityId: 'REQ-202610-801',
    severity: 'NOTICE',
    previousState: { status: 'submitted' },
    newState: { status: 'approved', currentStage: 'matching' },
    reason: 'Approved critical 4.0 L O+ refill request based on verified stockout prediction.',
  },
  {
    id: 'aud-004',
    timestamp: '2026-10-03T11:42:00Z',
    actorId: 'usr-hsp-nurse-02',
    actorName: 'Dr. Kavita Joshi (Obs & Gyn)',
    actorRole: 'hospital',
    organizationId: 'HSP-00124',
    organizationName: 'CityCare Hospital & Trauma Center',
    action: 'TRANSACTION_CREATED',
    entityType: 'TRANSACTION',
    entityId: 'TXN-20261003-10244',
    severity: 'NOTICE',
    newState: { quantity: -1.0, bloodGroup: 'O+', remainingStock: 4.0 },
    reason: 'Postpartum hemorrhage emergency protocol - verified transaction.',
  },
  {
    id: 'aud-005',
    timestamp: '2026-10-03T10:00:00Z',
    actorId: 'usr-admin-01',
    actorName: 'Alhaj Baig (Regional Director)',
    actorRole: 'admin',
    organizationId: 'RaktSetu-Network',
    action: 'LOGIN',
    entityType: 'SYSTEM',
    entityId: 'SESSION-ADM-01',
    severity: 'INFO',
    reason: 'Administrator authenticated into Central Network Command Node.',
  },
];

/**
 * Creates a fresh, mathematically consistent seed state for the demo
 */
export function createInitialSeedState(): RaktSetuLocalState {
  const now = new Date().toISOString();

  return {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    stateVersion: 101,

    session: {
      authenticated: true,
      userId: 'usr-admin-01',
      userName: 'Alhaj Baig (Regional Director)',
      email: 'demo.admin@raktsetu.network',
      organizationId: 'RaktSetu-Network',
      organizationName: 'RaktSetu Regional Network Command',
      role: 'admin',
    },

    organizations: INITIAL_ORGANIZATIONS,
    bloodBanks: INITIAL_BLOOD_BANKS_FULL,
    hospitalInventory: INITIAL_HOSPITAL_INVENTORY,
    transactions: INITIAL_TRANSACTIONS,
    requests: INITIAL_REQUESTS,
    reservations: INITIAL_RESERVATIONS,
    transfers: INITIAL_TRANSFERS,
    alerts: INITIAL_ALERTS,
    auditLogs: INITIAL_AUDIT_LOGS,
    systemEvents: [
      {
        id: 'evt-1',
        type: 'NETWORK_INITIALIZED',
        timestamp: now,
        actorId: 'SYSTEM',
        entityType: 'NETWORK',
        entityId: 'RaktSetu-Central',
        version: 101,
      },
    ],
    settings: INITIAL_SETTINGS,

    meta: {
      initializedAt: now,
      lastUpdatedAt: now,
      lastEventId: 'evt-1',
    },
  };
}
